import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv("student_data.csv")
print(df)
print("Average CGPA:",df["CGPA"].mean())
print("Average Credit:",df["Credit"].mean())
print("Average Age:",df["Age"].mean())
print("Median CGPA:",df["CGPA"].median())
print("Median Credit:",df["Credit"].median())
print("Median age:",df["Age"].median())
print("Mode CGPA:",df["CGPA"].mode())
print("Mode Credits:",df["Credit"].mode())
print("Mode Age:",df["Age"].mode())
print("Maximum CGPA:",df["CGPA"].max(),"Maximum Credit:",df["Credit"].max(),"Maximum Age:",df["Age"].max())
print("CGPA Variance:",df["CGPA"].var())
print("CGPA Standart Deviation:",df["CGPA"].std())
print("Credit Variance:",df["Credit"].var())
print("Credit Standard Deviation:",df["Credit"].std())
print(df.describe())
df.to_csv("student_data.csv",index=False)
df=pd.read_csv("student_data.csv")
print(df)
print("Count:")
print(df.count())
df.boxplot(column=["CGPA"])
plt.show()
plt.savefig("boxplot.png")
